### PR TITLE
pppd: Fix duplicate nameserver in resolv.conf

### PR DESCRIPTION
**Pull request by Dreshik**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@Dreshik: Can you sign-off?

@paulusmack: Can you look?

**Review by pali — APPROVED** [review]

**Comment by paulusmack** [comment]
The patch itself looks fine to me, but it does need a signoff.

**Comment by Neustradamus** [comment]
@Dreshik: Please look here: https://github.com/ppp-project/ppp/pull/337/checks?check_run_id=7234652362

**Comment by Neustradamus** [comment]
@Dreshik: There is a problem with the sign-off, can you look it?

**Pull request merged**
