### PR TITLE
Fix deficiencies found by shellcheck

### PR DESCRIPTION
**Pull request by Chocobo1**
* Fix deficiencies found by shellcheck on poff script
* Fix deficiencies found by shellcheck on pon script

Shellcheck: https://www.shellcheck.net/

### CODE REVIEW

**Comment by Chocobo1** [comment]
@paulusmack 
Please take a look.

**Comment by paulusmack** [comment]
I'm not really comfortable with a signoff from a users.noreply.github.com address.

**Comment by Chocobo1** [comment]
>I'm not really comfortable with a signoff from a users.noreply.github.com address.

Any other way to resolve it? co-author? or just take the patch and reapply under a different author (I'm fine with it).

An email address is just a communication method to contact the person and so is tagging on Github (for example: @Chocobo1). Github won't last forever but the same can also be said about email addresses...

**Comment by Neustradamus** [comment]
@Chocobo1: For example: https://docs.pi-hole.net/guides/github/how-to-signoff/

**Comment by Neustradamus** [comment]
@Chocobo1: Can you look for sign-off?
I have written a previous comment several days ago.

**Comment by enaess** [comment]
@thesamesam You able to review this? Change looks good to me

**Review by thesamesam — APPROVED** [review]

**Comment by paulusmack** [comment]
The main problem with this PR is still the signoff from a deliberately non-functional email address, which seems to me to be equivalent to no signoff at all.

**Comment by thesamesam** [comment]
I share your concern with that, but I'll note that despite the name, I think it does get forwarded to some legit email when I last asked someone using one. But it's still fair if you want to reject it, I wouldn't blame you.

**Comment by Neustradamus** [comment]
@Chocobo1: Any news?

**Comment by Neustradamus** [comment]
@enaess: @Chocobo1 has closed the PR. Can you look?

**Comment by Neustradamus** [comment]
@enaess: Have you added @Chocobo1 changes?

**Pull request closed without merging**
