### PR TITLE
CI: add automatic tests, enable ASAN build&test

### PR DESCRIPTION
**Pull request by chipitsine**
1. libpam is installed which enables it when running "configure"
2. cbcp is enabled
3. build step for running automatic tests added, i.e. "make check"
4. one more configuration is added, with ASAN (address sanitizer) enabled. it will prevent bugs like https://github.com/ppp-project/ppp/issues/392 (until proper fix is merged, ASAN job will fail)

### CODE REVIEW

**Comment by Neustradamus** [comment]
@RICCIARDI-Adrien: What do you think?

**Comment by enaess** [comment]
@chipitsine Could you please add some more notes to the PR description, just to summarize what the changes do?

**Comment by chipitsine** [comment]
I added descr few days ago.

however, maybe I should add inline comment ? people rarely read PR description

**Comment by enaess** [comment]
@chipitsine I think it is okay. It's just that merging changes here are limited by @paulusmack 's time and availability.

**Comment by Neustradamus** [comment]
@paulusmack: Have you looked?

**Pull request merged**
