### PR TITLE
Few more changes before 2.5.0 release

### PR DESCRIPTION
**Pull request by enaess**
Updating README with initial set of release notes for 2.5.0 version
Updating PLUGINS to reflect current set of changes to PPPD Plugin API
Adding LICENSE.* files to indicate the licenses that covers this project
Updating a few more header files that didn't have their licence information added (copied from their respective .c files).
Disable the building of static libraries (.a) by default, particularly for plugins

### CODE REVIEW

**Comment by Neustradamus** [comment]
@paulusmack: Can you look the @enaess PR?

**Comment by enaess** [comment]
Thank you for merging!

**Comment by bkuhls** [comment]
Please add the license files to https://github.com/ppp-project/ppp/blob/master/Makefile.am#L77 so they are included in the tarball, thanks!

**Comment by Neustradamus** [comment]
@enaess, @paulusmack: Have you seen the @bkuhls comment?

**Pull request merged**
