### PR TITLE
Adding pkgconfig support to pppd project

### PR DESCRIPTION
**Pull request by enaess**
This adds pppd.pc into $(INSTROOT)/$(LIBDIR)/pkgconfig. On some distributions
this would be /lib/pkgconfig, or /usr/lib/pkgconfig, but other distributions
may consider specifying --libdir=/usr/lib/x86_x64-linux-gnu/ and the pkgconfig
directory would be under that.

Manually cherry picking parts of two commits by @lkundrak from:
    https://github.com/NetworkManager/ppp/tree/lr/pkgconfig

Mainly, the difference between the original commit is not to replace DESTDIR
with "prefix". Leave DESTDIR alone, and add needed pkgconfig (pppd.pc.in)
as a part of the linux distribution (previously in pppd/plugin directory).

Signed-off-by: Eivind Naess <eivnaes@yahoo.com>

### CODE REVIEW

**Comment by enaess** [comment]
@Neustradamus @paulusmack What do you think?

**Comment by Neustradamus** [comment]
Thanks @enaess!
I hope a quick review from @paulusmack ^^

**Comment by enaess** [comment]
@Neustradamus - @RICCIARDI-Adrien Any idea what is going on here? 

```
 cd pppd; /usr/bin/make -w -j3 --jobserver-auth=3,4 install-devel
make[2]: warning: -j3 forced in submake: resetting jobserver mode.
make[2]: Entering directory '/home/runner/work/ppp/ppp/buildroot/output/build/pppd-3b2236b04d704e1424e294db1352383bb44d7e43/pppd'
mkdir -p /home/runner/work/ppp/ppp/buildroot/output/host/x86_64-buildroot-linux-musl/sysroot//home/runner/work/ppp/ppp/buildroot/output/host/x86_64-buildroot-linux-musl/sysroot//usr/include/pppd
install -c -m 644 ccp.h session.h chap-new.h ecp.h fsm.h ipcp.h ipxcp.h lcp.h magic.h md5.h patchlevel.h pathnames.h pppd.h upap.h eap.h md4.h chap_ms.h mppe.h sha1.h eap-tls.h pppcrypt.h tdb.h spinlock.h ipv6cp.h eui64.h /home/runner/work/ppp/ppp/buildroot/output/host/x86_64-buildroot-linux-musl/sysroot//home/runner/work/ppp/ppp/buildroot/output/host/x86_64-buildroot-linux-musl/sysroot//usr/include/pppd
make[2]: Leaving directory '/home/runner/work/ppp/ppp/buildroot/output/build/pppd-3b2236b04d704e1424e294db1352383bb44d7e43/pppd'
make[1]: Leaving directory '/home/runner/work/ppp/ppp/buildroot/output/build/pppd-3b2236b04d704e1424e294db1352383bb44d7e43'
>>> pppd 3b2236b04d704e1424e294db1352383bb44d7e43 Fixing libtool files
for la in $(find /home/runner/work/ppp/ppp/buildroot/output/host/x86_64-buildroot-linux-musl/sysroot/usr/lib* -name "*.la"); do \
	cp -a "${la}" "${la}.fixed" && \
	/usr/bin/sed -i -e "s:/home/runner/work/ppp/ppp/buildroot/output:@BASE_DIR@:g" \
		-e "s:/home/runner/work/ppp/ppp/buildroot/output/host/x86_64-buildroot-linux-musl/sysroot:@STAGING_DIR@:g" \
		 \
		-e "s:\(['= ]\)/usr:\\1@STAGING_DIR@/usr:g" \
		-e "s:\(['= ]\)/lib:\\1@STAGING_DIR@/lib:g" \
		 \
		-e "s:@STAGING_DIR@:/home/runner/work/ppp/ppp/buildroot/output/host/x86_64-buildroot-linux-musl/sysroot:g" \
		-e "s:@BASE_DIR@:/home/runner/work/ppp/ppp/buildroot/output:g" \
		"${la}.fixed" && \
	if cmp -s "${la}" "${la}.fixed"; then \
		rm -f "${la}.fixed"; \
	else \
		mv "${la}.fixed" "${la}"; \
	fi || exit 1; \
done
pppd: installs files in /home/runner/work/ppp/ppp/buildroot/output/host/x86_64-buildroot-linux-musl/sysroot//home/runner/work/ppp/ppp/buildroot/output
make: *** [package/pkg-generic.mk:294: /home/runner/work/ppp/ppp/buildroot/output/build/pppd-3b2236b04d704e1424e294db1352383bb44d7e43/.stamp_staging_installed] Error 1
Error: Process completed with exit code 2.
```

**Comment by RICCIARDI-Adrien** [comment]
Hi @enaess, I will try to reproduce the build error as soon as possible. I keep you updated.

**Comment by RICCIARDI-Adrien** [comment]
@enaess, I was to reproduce the same issue locally.
The last displayed path seems strange to me : `pppd: installs files in /home/runner/work/ppp/ppp/buildroot/output/host/x86_64-buildroot-linux-musl/sysroot//home/runner/work/ppp/ppp/buildroot/output`. Could two path variables be concatenated in your recent modifications ?

**Comment by enaess** [comment]
@RICCIARDI-Adrien that is quite possible, but am still not able to understand why or how. 

You able to help me setup a workflow like this locally? E.g. could you push a docker image to github and let me clone it? Or point me to documentation to setup this myself locally?

**Comment by enaess** [comment]
@RICCIARDI-Adrien - I think I figured it out based on your comments. Updated the commit. I'd still be interested in how I could set up a VM to run this locally for future triaging.

**Comment by enaess** [comment]
@paulusmack - What do you think?

**Comment by RICCIARDI-Adrien** [comment]
@enaess Great, you fixed the issue!
Here is my "quick test" setup with the architecture and libc that failed (it could be effectively a good idea to provide a Docker image, maybe it can be put somewhere on this repo for the developers to play with) :
```
git clone --depth=1 --branch=2020.11.1 https://git.busybox.net/buildroot

cd buildroot/package/pppd
# Allow package to build when musl libc is selected
sed -i '/depends on !BR2_TOOLCHAIN_USES_MUSL/d' Config.in
# Upstream version always needs OpenSSL
sed -i '/select BR2_PACKAGE_OPENSSL/c\\select BR2_PACKAGE_OPENSSL' Config.in
# Do not check for package hash, so there is no need to compute it
rm pppd.hash
# Buildroot patch is already applied upstream
rm -f 0001-pppd-Fix-bounds-check.patch
# Get package sources from head of master branch
sed -i "/PPPD_VERSION =/c\\PPPD_VERSION = bfffd94ad7455fb8cdf876b4b696c06756e9d1ee" pppd.mk
sed -i '/PPPD_SITE =/c\\PPPD_SITE = https://github.com/enaess/ppp' pppd.mk
sed -i '9iPPPD_SITE_METHOD = git' pppd.mk
# Plugin rp-pppoe has been renamed in "pppoe"
sed -i 's/rp-pppoe/pppoe/g' pppd.mk

cd ../..
echo "BR2_PACKAGE_PPPD=y" >> configs/qemu_x86_64_defconfig
echo "BR2_PACKAGE_PPPD_FILTER=y" >> configs/qemu_x86_64_defconfig
echo "BR2_PACKAGE_PPPD_RADIUS=y" >> configs/qemu_x86_64_defconfig
echo "BR2_PACKAGE_PPPD_OVERWRITE_RESOLV_CONF=y" >> configs/qemu_x86_64_defconfig

echo "BR2_TOOLCHAIN_BUILDROOT_MUSL=y" >> configs/qemu_x86_64_defconfig

make qemu_x86_64_defconfig
make
```

**Comment by enaess** [comment]
Thanks @RICCIARDI-Adrien - that command worked for me.

**Comment by Neustradamus** [comment]
Thanks @enaess, @paulusmack and @RICCIARDI-Adrien too!

**Pull request merged**
