### PR TITLE
pppd: Add pap-secrets and chap-secrets options

### PR DESCRIPTION
**Pull request by tpaukrt**
These options allow a user to specify paths to pap-secrets and chap-secrets files.

### CODE REVIEW

**Comment by paulusmack** [comment]
Letting a non-privileged user control authentication seems like a really bad idea.

**Comment by tpaukrt** [comment]
Added OPT_PRIV to both options.

**Comment by paulusmack** [comment]
Still needs explanation (in the commit message) of why we want such fine-grained control, as opposed to, say, using the `--sysconfdir` option when configuring.

**Comment by tpaukrt** [comment]
Added explanation to the commit message.

**Comment by Neustradamus** [comment]
@tpaukrt, @paulusmack: Can you check the @ua0lnj issue?
- https://github.com/ppp-project/ppp/issues/542

**Pull request merged**
