### PR TITLE
pppd: make pid directory before create the pid file

### PR DESCRIPTION
**Pull request by DragonBluep**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@paulusmack: Have you seen this @DragonBluep PR?

**Comment by paulusmack** [comment]
I think I'd prefer it without the #ifdef.

**Comment by DragonBluep** [comment]
> I think I'd prefer it without the #ifdef.

Fixed. Thanks.

**Comment by Neustradamus** [comment]
@paulusmack: It is good for you now? :)

**Pull request merged**
