### PR TITLE
 Add pkg-config support

### PR DESCRIPTION
**Pull request by lkundrak**
Hii,

plese review this and consider merging it. It will make it simpler for us to determine the location where to put the NetworkManger pppd plugin.

Thank you!
Lubo

### CODE REVIEW

**Comment by paulusmack** [comment]
This has several problems in the "Determine some more variables at configure time" commit.

- In pppd/plugins/pppoatm/Makefile.linux you have changed the mode for the plugin from 4550 to 455, which is wrong. Arguably the 4000 (setuid) bit doesn't really mean anything for a plugin, but if you want to change that, it's a separate change that should be a separate patch, and then the mode should be 555 not 455.

- In pppd/plugins/pppol2tp/Makefile.linux you change the symbol for the plugin directory from LIBDIR to PLUGINDIR but then still install the plugin to LIBDIR.

- In pppd/plugins/rp-pppoe/Makefile.linux you set PPPDVERSION to the version number but then use $(VERSION) in defining PLUGINDIR.

**Comment by lkundrak** [comment]
Thanks. Addressed the review.

I've also added one more change. That one is required so that the .pc file is "relocatable" -- the prefix is expanded later and thus can be overridden. That is useful when whoever consumes the file chooses an alternate installation prefix after the build is done (e.g. what autotools' "make distcheck" does when checking sanity of the installation).

**Comment by Neustradamus** [comment]
@lkundrak: Can you rebase your PR?

**Comment by Neustradamus** [comment]
@lkundrak: Can you rebase your PR?
Thanks in advance.

**Comment by Neustradamus** [comment]
@lkundrak: Can you rebase your PR?

**Comment by enaess** [comment]
I'd also vouch for this as maintenance of network-manager-sstp and sstp-client would be easier.

**Comment by Neustradamus** [comment]
@enaess: I think the best solution, badly, is to create a new PR... :/

**Comment by enaess** [comment]
@Neustradamus I'll have a look

**Comment by vincele** [comment]
Hello, should this PR be closed now that pkg-config has been merged ? c.f. #270

**Comment by enaess** [comment]
@lkundrak @paulusmack could you please close this PR?

**Pull request closed without merging**
