### PR TITLE
configure.ac: use consistent x${VAR} = x${VALUE} test

### PR DESCRIPTION
**Pull request by thesamesam**
May as well do it the same way throughout.

Signed-off-by: Sam James <sam@gentoo.org>

### CODE REVIEW

**Comment by Neustradamus** [comment]
@paulusmack, @enaess: What do you think?

**Comment by enaess** [comment]
I am okay with the change. Though, I have a fork/branch with similar fixes in it. No worries, I can merge / rebase

**Comment by enaess** [comment]
@thesamesam you can also peek at my current fork / ppp-autotools branch. I am hoping to refactor some of the headers as s a part of this step ... 

I could work in any suggestions (or take PRs) just so @paulusmack have to do a merge instead of getting pinged for each suggestion

**Comment by thesamesam** [comment]
@enaess I've got some additional changes (should apply cleanly on top of yours). Sounds good to me! I'll PR them to your repo, merge that branch in, then we'll do one large PR when it's all baked?

**Comment by enaess** [comment]
We could certainly do that. Just emailed @paulusmack so he is aware of the work in progress.

For this change in general, it can be merged and I can rebase.

**Comment by thesamesam** [comment]
I'll close this PR and I've filed https://github.com/enaess/ppp/pull/3 to make things easier? I hope that's OK, but if you want me to change stuff, let me know.

**Pull request closed without merging**
