### PR TITLE
CHAP Response add retransmission.

### PR DESCRIPTION
**Pull request by hanfezh**
CHAP Response add retransmission: transmited 10 times utils received SUCCESS or FAILURE, in 3 seconds interval.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@nomis: What do you think about this PR?

**Comment by nomis** [comment]
I've explained why retransmitting is a bad idea here: https://github.com/paulusmack/ppp/issues/87#issuecomment-595794742

This is a challenge/response authentication method and it is normal for the entire PPP session to be transparently transferred to a different LNS.

**Comment by Neustradamus** [comment]
@hanfezh: What do you think about @nomis comment?

At the same time, can you rebase and squash your commits and sign-off please?

**Comment by paulusmack** [comment]
> I've explained why retransmitting is a bad idea here: [#87 (comment)](https://github.com/paulusmack/ppp/issues/87#issuecomment-595794742)
> 
> This is a challenge/response authentication method and it is normal for the entire PPP session to be transparently transferred to a different LNS.

RFC1334 says "the authenticator MUST allow repeated Response packets after completing the Authentication phase". To be sure, the peer could be buggy, and we can provide ways to work around that, but we don't have to assume that the peer is buggy.

**Comment by Neustradamus** [comment]
@hanfezh: What do you think about @nomis and @paulusmack comments?

**Comment by Neustradamus** [comment]
@hanfezh: What do you think about @nomis and @paulusmack comments?

**Comment by Neustradamus** [comment]
@hanfezh: Soon two years after my latest comment here.

What do you think?

Thanks in advance.

**Comment by hanfezh** [comment]
> @hanfezh: Soon two years after my latest comment here.
> 
> What do you think?
> 
> Thanks in advance.

Hi @Neustradamus I think we can close this PR, since it's about 9 years and no one else has feedback.

**Pull request closed without merging**
