### PR TITLE
Put locks to /var/lock/ppp

### PR DESCRIPTION
**Pull request by yarda**
Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>

### CODE REVIEW

**Comment by paulusmack** [comment]
Since this is about locking the serial port, the original intention was very much to interact with any other program that might want to use the serial port (e.g. getty, kermit, uucp, etc.), not just other pppds, so using a pppd-specific location defeats the purpose.

For me to take this I would have to be convinced that no current Linux distro has any defined convention for coordinating access to serial ports between different programs, and the only possible use of the 'lock' option is to lock against other pppds.

**Comment by Neustradamus** [comment]
@yarda: Have you looked the @paulusmack comment?

**Comment by Neustradamus** [comment]
@yarda: Have you looked the @paulusmack comment?

**Comment by yarda** [comment]
@paulusmack thanks for info. It makes sense. It's not my patch, I am dropping it downstream.

**Pull request closed without merging**
