### PR TITLE
pppd/options.c: handle malloc failure

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@paulusmack, @enaess: Have you seen this PR?

**Comment by enaess** [comment]
Looks fine to me, but if malloc fails the state of the system is probably not going to make much of a difference by returning 1.

**Comment by chipitsine** [comment]
This one is not recoverable, but returning error is better than segfault

**Comment by paulusmack** [comment]
The more usual thing would be to call novm("environment variable") or some such.

**Comment by Neustradamus** [comment]
@paulusmack: @chipitsine has done changes, what do you think?

**Pull request merged**
