### PR TITLE
Allow users to use Engine and ID strings unmodified to the OpenSSL engine

### PR DESCRIPTION
**Pull request by enaess**
This change allows users to specify "cert" and "key" arguments where the prefix leading up to the ':' indicates the engine e.g. pkcs11, the entire string is passed down to the engine library which does the parsing. In the case of pkcs11.so (OpenSC project's libp11) engine for OpenSSL, it will now correctly parse the PKCS11 URI string (See RFC7512).

### CODE REVIEW

**Comment by enaess** [comment]
@jjkeijser - Could you please review this.

**Comment by jjkeijser** [comment]
just reviewed it:  this is not **fully** rfc7512 compliant, as that says you **shall** start with "pkcs11:"  while you are just checking for ":" ; I'd recommend to switch this to
```
if ( strncmp( certfile, "pkcs11:", 7 ) == 0 )
```
and similarly for
```
if ( strncmp( privkeyfile, "pkcs11:", 7 ) == 0 )
```
Other than that the patch looks fine.

**Comment by enaess** [comment]
@jjkeijser I did the consideration of just doing a strncmp("pkcs11:"..), but opted to keep it generic as the parsing is done by the pkcs11 library / module provided to OpenSSL. 

The generic mechanism now expects the <engine>:<identifier> as before. No documentation update is needed. If someone provides a different OpenSSL engine, they have a chance to look at the entire string. 

The title of the check-in and/or bug can be changed to remove the claim of support for the RFC. I can go either way ... Just let me know

Eivind

**Comment by jjkeijser** [comment]
Hi,

I think the easiest solution is to drop the rfc7512 compliance, or water it down a bit, to 'more in line with rfc7512'.
It's just that I think we should avoid claiming compliance which is not true. 

On 11 Jun 2021, 18:20, at 18:20, "Eivind Næss" ***@***.***> wrote:
***@***.*** I did the consideration of just doing a

**Comment by enaess** [comment]
I concur, and I'll have the updated fix some time this weekend.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by enaess** [comment]
@jjkeijser PR and CL updated. This closes issue #275

**Comment by enaess** [comment]
@paulusmack this PR is ready for merge.

**Pull request merged**
