### PR TITLE
Add RFC8044 dictionary compatibility for IPv4 address

### PR DESCRIPTION
**Pull request by EasyNetDev**
I've added RFC8044 dictirnary for ipv4addr.
New dictionary files are coming with this RADIUS attribute.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@paulusmack: What do you think?

**Comment by paulusmack** [comment]
The change looks OK but there is no signoff, and a line or two of description would be helpful.

**Comment by EasyNetDev** [comment]
Closing this one with #291. Added signoff for it.

**Comment by Neustradamus** [comment]
It has been merged: https://github.com/ppp-project/ppp/pull/291.

**Pull request closed without merging**
